"""relation added

Revision ID: 524fb3d9716b
Revises: 1afef28ad0bd
Create Date: 2023-08-08 11:26:33.254128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524fb3d9716b'
down_revision = '1afef28ad0bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('country_id', sa.Integer(), nullable=False))
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_city_id', table_name='city')
    op.create_foreign_key(None, 'city', 'country', ['country_id'], ['id'])
    op.alter_column('country', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_country_id', table_name='country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_country_id', 'country', ['id'], unique=False)
    op.alter_column('country', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_index('ix_city_id', 'city', ['id'], unique=False)
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('city', 'country_id')
    # ### end Alembic commands ###
